export interface SwitchRouteProps {
  loginModuleType : string;
  loginTabLabel : string;
  loginEmailAddressLabel : string;
  loginEmailAddressPlaceholder?: string;
  loginEmailMobileErrMessage: string;
  loginPasswordLabel : string;
  loginForgotPassWordmsg : string;
  loginResetLinkLabel : string;
  loginButton : string;
  extraBlockLoginText? : string;
  extraBlockLoginLinkText? : string;
  registrationTabLabel : string;
  registrationEmailAddress : string;
  registrationPassword :string;
  registrationConfirmPassword : string;
  registrationCtaLabel : string;
  registrationCtaLink : string;
  showLabel : string;
  hideLabel : string;
  extraBlockRegisterText? : string;
  extraBlockRegisterLinkText? : string;
  guestTabLabel : string;
  guestEmailAddressLabel : string;
  guestMobileNumberLabel : string;
  guestMobileNumberConfirmLabel: string;
  guestContinueLabel : string;
  emailFieldErrorMessage : string;
  validEmailFieldErrorMessage : string;
  passwordFieldErrorMessage : string;
  confirmPasswordFieldErrorMessage : string;
  validMobileNumberErrorMessage : string;
  mobileNumberNotMatchErrorMessage : string;
  mobileNumberMaxLength : string;
  mobileNumberFieldPattern : string;
  confirmPasswordFieldErrorMsg: string;
  errorEmailPatternValidMsg: string;
  errorPasswordPatternMinMsg: string;
  errorConfirmPasswordPatternNotMatchMsg: string;
  resetPwdTitle: string;
  resetPwdDescription: string;
  resetPwdEmailLabel: string;
  resetPwdMobileLabel: string;
  resetPwdButtonLabel: string;
  resetPwdButtonCancelLabel: string;
  extraBlockGuestText?: string;
  extraBlockGuestLinkText?: string;
}