import {SelectOption} from '../Select/types';

export interface PersonalDetailsFormProps {
  heading?: string;
  firstNameLabel: string;
  firstNamePlaceholder: string;
  orderDetailsCta:string;
  lastNameLabel: string;
  lastNamePlaceholder:string;
  emailAddressLabel:string;
  emailAddressPlaceholder: string;
  addressLabel:string;
  addressKeyInText:string;
  streetLabel: string;
  streetPlaceholder:string;
  houseNumberLabel:string;
  houseNumberPlaceholder:string;
  zipCodeLabel:string;
  zipCodePlaceholder:string;
  cityLabel:string;
  postalcodePlaceholder:string;
  cityPlaceholder:string;
  cities: SelectOption[];
  firstNameErrorMax:string;
  firstNameErrorRequired:string;
  firstNameErrorPattern:string;
  lastNameErrorMax:string;
  lastNameErrorRequired:string;
  lastNameErrorPattern:string;
  emailErrorMax:string;
  emailErrorRequired:string;
  emailErrorPattern:string;
  addressErrorRequired:string;
  streetLabelErrorMax:string;
  streetLabelErrorRequired:string;
  streetLabelErrorPattern:string;
  houseNumberErrorMax:string;
  houseNumberErrorRequired:string;
  houseNumberErrorPattern:string;
  zipCodeErrorMax:string;
  zipCodeErrorRequired:string;
  zipCodeErrorPattern:string;
  zipCodeErrorMin:string;
  cityErrorMax:string;
  cityErrorRequired:string;
  enterAddressManually: string;
  keyInAddress: string;
  saveAddress: string;
  yourPersonalDetailsLabel?: string;
}
